<?php
/**
 * Title: Data-center locations
 * Slug: monovm-blueprint/data-center-locations
 * Categories: monovm-blueprint, services
 * Description: An editable regional directory with location codes and availability text.
 * Viewport Width: 1280
 */
?>

<!-- wp:group {"align":"full","className":"monovm-blueprint-section","style":{"spacing":{"padding":{"top":"var:preset|spacing|90","right":"var:preset|spacing|70","bottom":"var:preset|spacing|90","left":"var:preset|spacing|70"}}},"backgroundColor":"surface-alt","textColor":"ink","layout":{"type":"constrained"}} -->
<div class="wp-block-group alignfull monovm-blueprint-section has-ink-color has-surface-alt-background-color has-text-color has-background" style="padding-top:var(--wp--preset--spacing--90);padding-right:var(--wp--preset--spacing--70);padding-bottom:var(--wp--preset--spacing--90);padding-left:var(--wp--preset--spacing--70)">
	<!-- wp:group {"align":"wide","layout":{"type":"constrained"}} -->
	<div class="wp-block-group alignwide">
		<!-- wp:columns {"verticalAlignment":"bottom"} -->
		<div class="wp-block-columns are-vertically-aligned-bottom">
			<!-- wp:column {"verticalAlignment":"bottom","width":"65%"} -->
			<div class="wp-block-column is-vertically-aligned-bottom" style="flex-basis:65%"><!-- wp:paragraph {"className":"monovm-blueprint-kicker","style":{"typography":{"letterSpacing":"0.08em","textTransform":"uppercase"}},"textColor":"signal","fontSize":"small","fontFamily":"technical"} --><p class="monovm-blueprint-kicker has-signal-color has-text-color has-technical-font-family has-small-font-size" style="letter-spacing:0.08em;text-transform:uppercase"><?php echo esc_html__( '07 / LOCATIONS', 'monovm-blueprint' ); ?></p><!-- /wp:paragraph --><!-- wp:heading {"level":2,"fontSize":"2-x-large"} --><h2 class="wp-block-heading has-2-x-large-font-size"><?php echo esc_html__( 'Publish a location directory customers can read.', 'monovm-blueprint' ); ?></h2><!-- /wp:heading --></div>
			<!-- /wp:column -->

			<!-- wp:column {"verticalAlignment":"bottom","width":"35%"} -->
			<div class="wp-block-column is-vertically-aligned-bottom" style="flex-basis:35%"><!-- wp:paragraph {"textColor":"muted"} --><p class="has-muted-color has-text-color"><?php echo esc_html__( 'Replace each region, city, code, and availability line with current information. No map is required.', 'monovm-blueprint' ); ?></p><!-- /wp:paragraph --></div>
			<!-- /wp:column -->
		</div>
		<!-- /wp:columns -->

		<!-- wp:columns {"align":"wide","style":{"spacing":{"margin":{"top":"var:preset|spacing|80"},"blockGap":{"left":"var:preset|spacing|60"}}}} -->
		<div class="wp-block-columns alignwide" style="margin-top:var(--wp--preset--spacing--80)">
			<!-- wp:column -->
			<div class="wp-block-column"><!-- wp:group {"className":"monovm-blueprint-panel","style":{"border":{"top":{"color":"var:preset|color|signal","width":"2px"},"right":{"color":"var:preset|color|line","width":"1px"},"bottom":{"color":"var:preset|color|line","width":"1px"},"left":{"color":"var:preset|color|line","width":"1px"}},"spacing":{"padding":{"top":"var:preset|spacing|70","right":"var:preset|spacing|70","bottom":"var:preset|spacing|70","left":"var:preset|spacing|70"}}},"backgroundColor":"surface","layout":{"type":"constrained"}} --><div class="wp-block-group monovm-blueprint-panel has-surface-background-color has-background" style="border-top-color:var(--wp--preset--color--signal);border-top-width:2px;border-right-color:var(--wp--preset--color--line);border-right-width:1px;border-bottom-color:var(--wp--preset--color--line);border-bottom-width:1px;border-left-color:var(--wp--preset--color--line);border-left-width:1px;padding-top:var(--wp--preset--spacing--70);padding-right:var(--wp--preset--spacing--70);padding-bottom:var(--wp--preset--spacing--70);padding-left:var(--wp--preset--spacing--70)"><!-- wp:paragraph {"textColor":"signal","fontSize":"small","fontFamily":"technical"} --><p class="has-signal-color has-text-color has-technical-font-family has-small-font-size"><?php echo esc_html__( 'REGION 01', 'monovm-blueprint' ); ?></p><!-- /wp:paragraph --><!-- wp:heading {"level":3,"fontSize":"large"} --><h3 class="wp-block-heading has-large-font-size"><?php echo esc_html__( 'Region name', 'monovm-blueprint' ); ?></h3><!-- /wp:heading --><!-- wp:separator {"backgroundColor":"line"} --><hr class="wp-block-separator has-text-color has-line-color has-alpha-channel-opacity has-line-background-color has-background"/><!-- /wp:separator --><!-- wp:paragraph --><p><strong><?php echo esc_html__( 'City / facility', 'monovm-blueprint' ); ?></strong><br><?php echo esc_html__( 'Location code: CODE-01', 'monovm-blueprint' ); ?><br><?php echo esc_html__( 'Availability: replace with current status', 'monovm-blueprint' ); ?></p><!-- /wp:paragraph --><!-- wp:paragraph --><p><strong><?php echo esc_html__( 'City / facility', 'monovm-blueprint' ); ?></strong><br><?php echo esc_html__( 'Location code: CODE-02', 'monovm-blueprint' ); ?><br><?php echo esc_html__( 'Availability: replace with current status', 'monovm-blueprint' ); ?></p><!-- /wp:paragraph --></div><!-- /wp:group --></div>
			<!-- /wp:column -->

			<!-- wp:column -->
			<div class="wp-block-column"><!-- wp:group {"className":"monovm-blueprint-panel","style":{"border":{"top":{"color":"var:preset|color|signal","width":"2px"},"right":{"color":"var:preset|color|line","width":"1px"},"bottom":{"color":"var:preset|color|line","width":"1px"},"left":{"color":"var:preset|color|line","width":"1px"}},"spacing":{"padding":{"top":"var:preset|spacing|70","right":"var:preset|spacing|70","bottom":"var:preset|spacing|70","left":"var:preset|spacing|70"}}},"backgroundColor":"surface","layout":{"type":"constrained"}} --><div class="wp-block-group monovm-blueprint-panel has-surface-background-color has-background" style="border-top-color:var(--wp--preset--color--signal);border-top-width:2px;border-right-color:var(--wp--preset--color--line);border-right-width:1px;border-bottom-color:var(--wp--preset--color--line);border-bottom-width:1px;border-left-color:var(--wp--preset--color--line);border-left-width:1px;padding-top:var(--wp--preset--spacing--70);padding-right:var(--wp--preset--spacing--70);padding-bottom:var(--wp--preset--spacing--70);padding-left:var(--wp--preset--spacing--70)"><!-- wp:paragraph {"textColor":"signal","fontSize":"small","fontFamily":"technical"} --><p class="has-signal-color has-text-color has-technical-font-family has-small-font-size"><?php echo esc_html__( 'REGION 02', 'monovm-blueprint' ); ?></p><!-- /wp:paragraph --><!-- wp:heading {"level":3,"fontSize":"large"} --><h3 class="wp-block-heading has-large-font-size"><?php echo esc_html__( 'Region name', 'monovm-blueprint' ); ?></h3><!-- /wp:heading --><!-- wp:separator {"backgroundColor":"line"} --><hr class="wp-block-separator has-text-color has-line-color has-alpha-channel-opacity has-line-background-color has-background"/><!-- /wp:separator --><!-- wp:paragraph --><p><strong><?php echo esc_html__( 'City / facility', 'monovm-blueprint' ); ?></strong><br><?php echo esc_html__( 'Location code: CODE-03', 'monovm-blueprint' ); ?><br><?php echo esc_html__( 'Availability: replace with current status', 'monovm-blueprint' ); ?></p><!-- /wp:paragraph --><!-- wp:paragraph --><p><strong><?php echo esc_html__( 'City / facility', 'monovm-blueprint' ); ?></strong><br><?php echo esc_html__( 'Location code: CODE-04', 'monovm-blueprint' ); ?><br><?php echo esc_html__( 'Availability: replace with current status', 'monovm-blueprint' ); ?></p><!-- /wp:paragraph --></div><!-- /wp:group --></div>
			<!-- /wp:column -->

			<!-- wp:column -->
			<div class="wp-block-column"><!-- wp:group {"className":"monovm-blueprint-panel","style":{"border":{"top":{"color":"var:preset|color|signal","width":"2px"},"right":{"color":"var:preset|color|line","width":"1px"},"bottom":{"color":"var:preset|color|line","width":"1px"},"left":{"color":"var:preset|color|line","width":"1px"}},"spacing":{"padding":{"top":"var:preset|spacing|70","right":"var:preset|spacing|70","bottom":"var:preset|spacing|70","left":"var:preset|spacing|70"}}},"backgroundColor":"surface","layout":{"type":"constrained"}} --><div class="wp-block-group monovm-blueprint-panel has-surface-background-color has-background" style="border-top-color:var(--wp--preset--color--signal);border-top-width:2px;border-right-color:var(--wp--preset--color--line);border-right-width:1px;border-bottom-color:var(--wp--preset--color--line);border-bottom-width:1px;border-left-color:var(--wp--preset--color--line);border-left-width:1px;padding-top:var(--wp--preset--spacing--70);padding-right:var(--wp--preset--spacing--70);padding-bottom:var(--wp--preset--spacing--70);padding-left:var(--wp--preset--spacing--70)"><!-- wp:paragraph {"textColor":"signal","fontSize":"small","fontFamily":"technical"} --><p class="has-signal-color has-text-color has-technical-font-family has-small-font-size"><?php echo esc_html__( 'REGION 03', 'monovm-blueprint' ); ?></p><!-- /wp:paragraph --><!-- wp:heading {"level":3,"fontSize":"large"} --><h3 class="wp-block-heading has-large-font-size"><?php echo esc_html__( 'Region name', 'monovm-blueprint' ); ?></h3><!-- /wp:heading --><!-- wp:separator {"backgroundColor":"line"} --><hr class="wp-block-separator has-text-color has-line-color has-alpha-channel-opacity has-line-background-color has-background"/><!-- /wp:separator --><!-- wp:paragraph --><p><strong><?php echo esc_html__( 'City / facility', 'monovm-blueprint' ); ?></strong><br><?php echo esc_html__( 'Location code: CODE-05', 'monovm-blueprint' ); ?><br><?php echo esc_html__( 'Availability: replace with current status', 'monovm-blueprint' ); ?></p><!-- /wp:paragraph --><!-- wp:paragraph --><p><strong><?php echo esc_html__( 'City / facility', 'monovm-blueprint' ); ?></strong><br><?php echo esc_html__( 'Location code: CODE-06', 'monovm-blueprint' ); ?><br><?php echo esc_html__( 'Availability: replace with current status', 'monovm-blueprint' ); ?></p><!-- /wp:paragraph --></div><!-- /wp:group --></div>
			<!-- /wp:column -->
		</div>
		<!-- /wp:columns -->
	</div>
	<!-- /wp:group -->
</div>
<!-- /wp:group -->
